#!/usr/bin/python
# -*- coding: utf-8 -*-
import smtplib, sys, ConfigParser, os, datetime

inicio=datetime.datetime.now()

config = ConfigParser.ConfigParser()
config.read("/etc/mail-clamav-report/mail-clamav-report.cfg")
try:
    server=config.get("smtp","smtpserver" )
    user=config.get("smtp","user")
    password=config.get("smtp","pass")
    to=config.get("user","to")
except:
    print ("Error con el fichero de configuración /etc/mail-clamav-report/mail-clamav-report.cfg")    


f=os.popen("clamscan -ir /")
report=f.read()
f.close()

message = """From: mail-clamav-report
To: """+to+"""
Subject: mail-clamav-report

"""+report+ """
------------------------
El proceso ha durado: """ + str(datetime.datetime.now()-inicio)

try:
    server = smtplib.SMTP(server)
#    server.set_debuglevel(1)
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login(user,password)
except:
    print "Error: unable to send email"

server.sendmail("mail-clamav-report", to, message)
server.quit()
