#!/usr/bin/python
# -*- coding: utf-8 -*-
import smtplib, sys, ConfigParser, os, datetime

inicio=datetime.datetime.now()

config = ConfigParser.ConfigParser()
config.read("/etc/mail-clamav-report/mail-clamav-report.cfg")
try:
    servidor=config.get("smtp","smtpserver" )
    user=config.get("smtp","user")
    password=config.get("smtp","pass")
    to=config.get("user","to")
except:
    print ("Error con el fichero de configuración /etc/mail-clamav-report/mail-clamav-report.cfg")    


name=os.popen("hostname").read()
f=os.popen("hostname -d")
name=name[:-1]+"."+f.read()[:-1]
f.close()

f=os.popen("nice -n 19 clamscan -ir /")
report=f.read()
f.close()

message = """From: Mail-clamav-report
To: """ + to + """
Content-Type: text/plain; charset=UTF-8
Subject: Mail-clamav-report from """ + name + """

""" + report + """
------------------------
""" + name + """: el proceso ha durado: """ + str(datetime.datetime.now()-inicio)


try:
    server = smtplib.SMTP(servidor)
#    server.set_debuglevel(1)
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login(user,password)
except:
    print "Error: unable to send email"

server.sendmail("mail-clamav-report", to, message)
server.quit()
